from game_state import Allocation
from bot_strategy import BotStrategy


HUMAN_WON_OPENING_BOOK = [
    {
        "name": "treasure_shipyard_shield",
        "source": "Human wins vs Port Reaper and The Red Tide",
        "anti_aggro": True,
        "turns": {
            1: {
                "allocation": Allocation(guard=3),
                "buy_actions": ["launch_treasure", "start_shipyard"],
            },
            2: {
                "allocation": Allocation(guard=2),
                "buy_actions": [],
            },
            3: {
                "allocation": Allocation(guard=1),
                "buy_actions": ["launch_treasure", "buy_ships"],
            },
        },
    },
    {
        "name": "trade_guard_shipyard",
        "source": "Human win vs Bastion Corsair",
        "anti_aggro": True,
        "turns": {
            1: {
                "allocation": Allocation(guard=3),
                "buy_actions": ["launch_treasure", "start_shipyard"],
            },
            2: {
                "allocation": Allocation(trade=2, guard=1),
                "buy_actions": [],
            },
            3: {
                "allocation": Allocation(),
                "buy_actions": ["launch_treasure", "buy_ships"],
            },
        },
    },
    {
        "name": "balanced_treasure_pressure",
        "source": "Human wins vs Black Ledger and Builder",
        "turns": {
            1: {
                "allocation": Allocation(trade=1, raid=1, guard=1),
                "buy_actions": ["launch_treasure", "buy_ships"],
            },
            2: {
                "allocation": Allocation(trade=1, guard=3),
                "buy_actions": [],
            },
            3: {
                "allocation": Allocation(trade=2, guard=2),
                "buy_actions": ["launch_treasure", "buy_ships"],
            },
        },
    },
    {
        "name": "raid_treasure_snowball",
        "source": "Human wins vs Privateer and Merchant",
        "turns": {
            1: {
                "allocation": Allocation(raid=3),
                "buy_actions": ["launch_treasure", "buy_ships"],
            },
            2: {
                "allocation": Allocation(raid=2, guard=2),
                "buy_actions": ["start_shipyard"],
            },
            3: {
                "allocation": Allocation(trade=1, raid=3, guard=1),
                "buy_actions": ["launch_treasure", "start_trade_guild", "buy_ships"],
            },
        },
    },
    {
        "name": "dock_guard_treasure",
        "source": "Current-rule human wins vs Admiral and Opportunist",
        "turns": {
            1: {
                "allocation": Allocation(guard=3),
                "buy_actions": ["launch_treasure", "build_fishing_dock", "buy_ships"],
            },
            2: {
                "allocation": Allocation(raid=2, guard=2),
                "buy_actions": [],
            },
            3: {
                "allocation": Allocation(raid=3),
                "buy_actions": ["buy_fire_ship_plans", "launch_treasure", "buy_ships"],
            },
        },
    },
    {
        "name": "guild_dock_buildout",
        "source": "Current-rule human win vs Corsair Spark",
        "turns": {
            1: {
                "allocation": Allocation(guard=3),
                "buy_actions": ["start_trade_guild", "build_fishing_dock"],
            },
            2: {
                "allocation": Allocation(),
                "buy_actions": [],
            },
            3: {
                "allocation": Allocation(raid=3),
                "buy_actions": ["start_shipyard", "hire_guard_captain"],
            },
        },
    },
    {
        "name": "guard_captain_harbor_lock",
        "source": "Current-rule human win vs Harbor Lock",
        "turns": {
            1: {
                "allocation": Allocation(trade=3),
                "buy_actions": ["launch_treasure", "buy_ships"],
            },
            2: {
                "allocation": Allocation(trade=1, guard=4),
                "buy_actions": ["hire_guard_captain"],
            },
            3: {
                "allocation": Allocation(trade=1, raid=1, guard=3),
                "buy_actions": [
                    "start_shipyard",
                    "build_fishing_dock",
                    "hire_guard_captain",
                    "buy_fire_ship_plans",
                ],
            },
        },
    },
]


def default_bot_strategies():
    return [
        BotStrategy(
            name="Merchant",
            trade_weight=4.0,
            raid_weight=0.8,
            guard_weight=1.8,
            fire_weight=0.2,
            build_priority=[
                "shipyard",
                "trade_guild",
                "fishing_dock",
                "fishing_boat",
                "guard_captain",
                "fort",
            ],
            convoy_bias=0.75,
            ship_bias=0.75,
            shipyard_bias=0.85,
            fort_bias=0.15,
            trade_guild_bias=0.7,
            fishing_dock_bias=0.65,
            fishing_boat_bias=0.7,
            guard_captain_bias=0.12,
            fire_plans_bias=0.05,
            construction_idle_bias=0.55,
        ),
        BotStrategy(
            name="Privateer",
            trade_weight=1.4,
            raid_weight=4.0,
            guard_weight=1.1,
            fire_weight=1.2,
            build_priority=[
                "fire_plans",
                "shipyard",
                "fishing_dock",
                "guard_captain",
                "fort",
            ],
            convoy_bias=0.35,
            ship_bias=0.95,
            shipyard_bias=0.45,
            fort_bias=0.08,
            trade_guild_bias=0.03,
            fishing_dock_bias=0.12,
            fishing_boat_bias=0.08,
            guard_captain_bias=0.05,
            fire_plans_bias=0.55,
            construction_idle_bias=0.35,
        ),
        BotStrategy(
            name="Builder",
            trade_weight=2.4,
            raid_weight=1.1,
            guard_weight=2.0,
            fire_weight=0.4,
            build_priority=[
                "shipyard",
                "fort",
                "trade_guild",
                "fishing_dock",
                "fishing_boat",
                "guard_captain",
            ],
            convoy_bias=0.55,
            ship_bias=0.65,
            shipyard_bias=0.85,
            fort_bias=0.7,
            trade_guild_bias=0.55,
            fishing_dock_bias=0.45,
            fishing_boat_bias=0.45,
            guard_captain_bias=0.15,
            fire_plans_bias=0.08,
            construction_idle_bias=0.8,
        ),
        BotStrategy(
            name="Admiral",
            trade_weight=2.2,
            raid_weight=2.2,
            guard_weight=2.1,
            fire_weight=0.8,
            build_priority=[
                "shipyard",
                "fire_plans",
                "fort",
                "fishing_dock",
                "guard_captain",
            ],
            convoy_bias=0.6,
            ship_bias=0.85,
            shipyard_bias=0.7,
            fort_bias=0.35,
            trade_guild_bias=0.15,
            fishing_dock_bias=0.25,
            fishing_boat_bias=0.2,
            guard_captain_bias=0.12,
            fire_plans_bias=0.45,
            construction_idle_bias=0.55,
        ),
        BotStrategy(
            name="Opportunist",
            trade_weight=2.0,
            raid_weight=2.8,
            guard_weight=1.4,
            fire_weight=0.9,
            build_priority=["shipyard", "trade_guild", "fire_plans"],
            convoy_bias=0.5,
            ship_bias=0.9,
        ),
        BotStrategy(
            name="Human Shadow",
            trade_weight=5.2,
            raid_weight=1.0,
            guard_weight=1.05,
            fire_weight=0.06,
            build_priority=[
                "shipyard",
                "trade_guild",
                "fishing_dock",
                "fishing_boat",
                "guard_captain",
                "fort",
                "fire_plans",
            ],
            convoy_bias=0.65,
            ship_bias=0.9,
            shipyard_bias=0.72,
            fort_bias=0.35,
            trade_guild_bias=0.6,
            fishing_dock_bias=0.7,
            fishing_boat_bias=0.75,
            guard_captain_bias=0.35,
            fire_plans_bias=0.4,
            construction_idle_bias=0.72,
            opening_book=HUMAN_WON_OPENING_BOOK,
        ),
        BotStrategy(
            name="Tide Reader",
            trade_weight=2.4,
            raid_weight=2.4,
            guard_weight=2.0,
            fire_weight=0.8,
            build_priority=[
                "shipyard",
                "trade_guild",
                "fishing_dock",
                "fishing_boat",
                "fire_plans",
                "guard_captain",
                "fort",
            ],
            convoy_bias=0.45,
            ship_bias=0.8,
            shipyard_bias=0.55,
            fort_bias=0.25,
            trade_guild_bias=0.4,
            fishing_dock_bias=0.55,
            fishing_boat_bias=0.55,
            guard_captain_bias=0.18,
            fire_plans_bias=0.35,
            construction_idle_bias=0.6,
            adaptive=True,
            adaptation_strength=1.0,
            adaptation_turns=3,
        ),
        BotStrategy(
            name="Port Reaper",
            trade_weight=1.4,
            raid_weight=3.33,
            guard_weight=0.05,
            fire_weight=3.07,
            build_priority=[],
            convoy_bias=0.03,
            ship_bias=0.74,
        ),
        BotStrategy(
            name="Harbor Lock",
            trade_weight=4.72,
            raid_weight=0.68,
            guard_weight=3.6,
            fire_weight=2.0,
            build_priority=[],
            convoy_bias=0.18,
            ship_bias=0.9,
        ),
        BotStrategy(
            name="Corsair Spark",
            trade_weight=4.4,
            raid_weight=4.01,
            guard_weight=1.55,
            fire_weight=4.31,
            build_priority=[],
            convoy_bias=0.69,
            ship_bias=0.16,
        ),
        BotStrategy(
            name="Storm Reaver",
            trade_weight=2.84,
            raid_weight=3.95,
            guard_weight=2.19,
            fire_weight=4.61,
            build_priority=[],
            convoy_bias=0.32,
            ship_bias=0.74,
        ),
        BotStrategy(
            name="Iron Tempest",
            trade_weight=2.61,
            raid_weight=4.06,
            guard_weight=2.4,
            fire_weight=4.44,
            build_priority=[],
            convoy_bias=0.04,
            ship_bias=0.8,
        ),
        BotStrategy(
            name="Black Ledger",
            trade_weight=0.76,
            raid_weight=4.8,
            guard_weight=0.93,
            fire_weight=2.28,
            build_priority=[],
            convoy_bias=0.0,
            ship_bias=0.64,
            shipyard_bias=0.43,
            fort_bias=0.02,
            trade_guild_bias=0.12,
            guard_captain_bias=0.08,
            fire_plans_bias=0.12,
            construction_idle_bias=0.74,
        ),
        BotStrategy(
            name="Bastion Corsair",
            trade_weight=0.74,
            raid_weight=4.58,
            guard_weight=0.21,
            fire_weight=1.7,
            build_priority=[],
            convoy_bias=0.0,
            ship_bias=0.46,
            shipyard_bias=0.23,
            fort_bias=0.21,
            trade_guild_bias=0.08,
            guard_captain_bias=0.01,
            fire_plans_bias=0.04,
            construction_idle_bias=0.69,
        ),
        BotStrategy(
            name="Harbor Harvest",
            trade_weight=0.17,
            raid_weight=4.88,
            guard_weight=2.10,
            fire_weight=0.22,
            build_priority=[
                "fishing_dock",
                "shipyard",
                "fire_plans",
                "fishing_boat",
            ],
            convoy_bias=0.00,
            ship_bias=0.40,
            shipyard_bias=0.07,
            fort_bias=0.74,
            trade_guild_bias=0.29,
            fishing_dock_bias=1.00,
            fishing_boat_bias=0.99,
            guard_captain_bias=0.41,
            fire_plans_bias=0.34,
            construction_idle_bias=0.61,
        ),
        BotStrategy(
            name="Reef Tyrant",
            trade_weight=0.19,
            raid_weight=4.66,
            guard_weight=0.01,
            fire_weight=0.27,
            build_priority=[
                "fishing_boat",
                "fort",
                "fishing_dock",
                "shipyard",
                "fire_plans",
                "trade_guild",
            ],
            convoy_bias=0.00,
            ship_bias=0.80,
            shipyard_bias=0.04,
            fort_bias=0.24,
            trade_guild_bias=0.06,
            fishing_dock_bias=0.91,
            fishing_boat_bias=0.70,
            guard_captain_bias=0.10,
            fire_plans_bias=0.94,
            construction_idle_bias=0.72,
        ),
        BotStrategy(
            name="Reef Bloom",
            trade_weight=0.00,
            raid_weight=1.12,
            guard_weight=0.09,
            fire_weight=3.74,
            build_priority=[
                "fishing_dock",
                "dry_dock",
                "fishing_boat",
                "shipyard",
                "guard_captain",
                "fort",
                "fire_plans",
            ],
            convoy_bias=0.00,
            ship_bias=0.14,
            shipyard_bias=0.10,
            fort_bias=0.82,
            trade_guild_bias=0.00,
            guard_captain_bias=0.18,
            fire_plans_bias=0.15,
            fishing_dock_bias=0.99,
            fishing_boat_bias=0.97,
            dry_dock_bias=0.68,
            repair_bias=0.83,
            construction_idle_bias=0.43,
        ),
        BotStrategy(
            name="The Red Tide",
            trade_weight=0.33,
            raid_weight=4.89,
            guard_weight=0.00,
            fire_weight=1.41,
            build_priority=["shipyard"],
            convoy_bias=0.00,
            ship_bias=0.85,
            shipyard_bias=0.25,
            fort_bias=0.06,
            trade_guild_bias=0.01,
            guard_captain_bias=0.00,
            fire_plans_bias=0.00,
            construction_idle_bias=0.85,
        ),
        BotStrategy(
            name="Signal Black",
            trade_weight=0.02,
            raid_weight=4.16,
            guard_weight=0.02,
            fire_weight=0.17,
            build_priority=[],
            convoy_bias=0.01,
            ship_bias=0.89,
            shipyard_bias=0.03,
            fort_bias=0.03,
            trade_guild_bias=0.00,
            guard_captain_bias=0.08,
            fire_plans_bias=0.00,
            fishing_dock_bias=0.00,
            fishing_boat_bias=0.90,
            construction_idle_bias=0.46,
        ),
    ]


def strategy_names():
    return [strategy.name for strategy in default_bot_strategies()]


def find_strategy(name):
    normalized_name = name.strip().lower()
    for strategy in default_bot_strategies():
        if strategy.name.lower() == normalized_name:
            return strategy

    available = ", ".join(strategy_names())
    raise ValueError(f"Unknown AI strategy '{name}'. Available strategies: {available}.")
