# bot_roster.py
"""Module for managing the default bot strategies.
This module defines a set of default bot strategies with various playstyles and parameters. 
It also provides functions to retrieve the list of strategy names and to find a strategy by name.
Key components include:
- BotStrategy: A class representing a bot's strategy, including build priorities and weight fields.
- default_bot_strategies: A function that returns a list of predefined BotStrategy 
instances representing different bot playstyles.
- strategy_names: A function that returns a list of the names of the default bot strategies.
- find_strategy: A function that takes a strategy name as input and returns the corresponding 
BotStrategy instance from the default roster, or raises a ValueError if the name is not found.
"""


# Imports
from bot_strategy import BotStrategy
from bot_openings import HUMAN_WON_OPENING_BOOK, NASH_CORE_OPENING_BOOK


def default_bot_strategies():
    """
    Each BotStrategy includes parameters such as trade_weight, raid_weight, guard_weight, fire_weight, build_priority, and various biases that influence the bot's decision-making during the game. Some strategies also include an opening_book that defines specific actions for the early turns of the game.
    
    Returns:
        list: A list of BotStrategy instances, each representing a different bot strategy with unique parameters and playstyle.
    """
    return [
        BotStrategy(
            name="Merchant",
            trade_weight=4.0,
            raid_weight=0.8,
            guard_weight=1.8,
            fire_weight=0.2,
            build_priority=[
                "shipyard",
                "trade_guild",
                "fishing_dock",
                "fishing_boat",
                "guard_captain",
                "fort",
            ],
            convoy_bias=0.75,
            ship_bias=0.75,
            shipyard_bias=0.85,
            fort_bias=0.15,
            trade_guild_bias=0.7,
            fishing_dock_bias=0.65,
            fishing_boat_bias=0.7,
            guard_captain_bias=0.12,
            fire_plans_bias=0.05,
            construction_idle_bias=0.55,
        ),
        BotStrategy(
            name="Privateer",
            trade_weight=1.4,
            raid_weight=4.0,
            guard_weight=1.1,
            fire_weight=1.2,
            build_priority=[
                "fire_plans",
                "shipyard",
                "fishing_dock",
                "guard_captain",
                "fort",
            ],
            convoy_bias=0.35,
            ship_bias=0.95,
            shipyard_bias=0.45,
            fort_bias=0.08,
            trade_guild_bias=0.03,
            fishing_dock_bias=0.12,
            fishing_boat_bias=0.08,
            guard_captain_bias=0.05,
            fire_plans_bias=0.55,
            construction_idle_bias=0.35,
        ),
        BotStrategy(
            name="Builder",
            trade_weight=2.4,
            raid_weight=1.1,
            guard_weight=2.0,
            fire_weight=0.4,
            build_priority=[
                "shipyard",
                "fort",
                "trade_guild",
                "fishing_dock",
                "fishing_boat",
                "guard_captain",
            ],
            convoy_bias=0.55,
            ship_bias=0.65,
            shipyard_bias=0.85,
            fort_bias=0.7,
            trade_guild_bias=0.55,
            fishing_dock_bias=0.45,
            fishing_boat_bias=0.45,
            guard_captain_bias=0.15,
            fire_plans_bias=0.08,
            construction_idle_bias=0.8,
        ),
        BotStrategy(
            name="Admiral",
            trade_weight=2.2,
            raid_weight=2.2,
            guard_weight=2.1,
            fire_weight=0.8,
            build_priority=[
                "shipyard",
                "fire_plans",
                "fort",
                "fishing_dock",
                "guard_captain",
            ],
            convoy_bias=0.6,
            ship_bias=0.85,
            shipyard_bias=0.7,
            fort_bias=0.35,
            trade_guild_bias=0.15,
            fishing_dock_bias=0.25,
            fishing_boat_bias=0.2,
            guard_captain_bias=0.12,
            fire_plans_bias=0.45,
            construction_idle_bias=0.55,
        ),
        BotStrategy(
            name="Opportunist",
            trade_weight=2.0,
            raid_weight=2.8,
            guard_weight=1.4,
            fire_weight=0.9,
            build_priority=["shipyard", "trade_guild", "fire_plans"],
            convoy_bias=0.5,
            ship_bias=0.9,
        ),
        BotStrategy(
            name="Human Shadow",

            trade_weight=3.25,
            raid_weight=3.85,
            guard_weight=2.15,
            fire_weight=2.75,

            build_priority=[
                "shipyard",
                "guard_captain",
                "trade_guild",
                "fishing_dock",
                "fishing_boat",
                "fort",
                "fire_plans",
                "dockhouse",
                "administrator",
                "dry_dock",
                "admiralty",
                "admiral",
            ],

            convoy_bias=0.74,
            ship_bias=0.92,

            shipyard_bias=0.82,
            fort_bias=0.54,
            trade_guild_bias=0.68,
            administrator_bias=0.52,

            guard_captain_bias=0.64,
            fire_plans_bias=0.58,

            fishing_dock_bias=0.48,
            fishing_boat_bias=0.42,

            dockhouse_bias=0.36,
            dockhand_bias=0.30,
            dockhand_repair_bias=0.34,
            dockhand_boatwright_bias=0.45,

            dry_dock_bias=0.44,
            admiralty_bias=0.36,
            admiral_bias=0.24,
            overtime_bias=0.38,

            repair_bias=0.48,
            construction_idle_bias=0.10,

            adaptive=True,
            adaptation_strength=0.75,
            adaptation_turns=3,
        ),
        BotStrategy(
            name="Tide Reader",
            trade_weight=2.4,
            raid_weight=2.4,
            guard_weight=2.0,
            fire_weight=0.8,
            build_priority=[
                "shipyard",
                "trade_guild",
                "fishing_dock",
                "fishing_boat",
                "fire_plans",
                "guard_captain",
                "fort",
            ],
            convoy_bias=0.45,
            ship_bias=0.8,
            shipyard_bias=0.55,
            fort_bias=0.25,
            trade_guild_bias=0.4,
            fishing_dock_bias=0.55,
            fishing_boat_bias=0.55,
            guard_captain_bias=0.18,
            fire_plans_bias=0.35,
            construction_idle_bias=0.6,
            adaptive=True,
            adaptation_strength=1.0,
            adaptation_turns=3,
        ),
        BotStrategy(
            name="Nash Admiral",
            trade_weight=2.1,
            raid_weight=3.0,
            guard_weight=3.2,
            fire_weight=0.55,
            build_priority=[
                "shipyard",
                "fort",
                "guard_captain",
                "fishing_dock",
                "fishing_boat",
                "trade_guild",
                "dry_dock",
                "fire_plans",
                "admiralty",
                "admiral",
            ],
            convoy_bias=0.12,
            ship_bias=0.90,
            shipyard_bias=0.92,
            fort_bias=0.58,
            trade_guild_bias=0.34,
            fishing_dock_bias=0.64,
            fishing_boat_bias=0.58,
            guard_captain_bias=0.58,
            fire_plans_bias=0.22,
            dry_dock_bias=0.36,
            admiralty_bias=0.12,
            admiral_bias=0.12,
            overtime_bias=0.12,
            repair_bias=0.58,
            construction_idle_bias=0.48,
            opening_book=NASH_CORE_OPENING_BOOK,
        ),
        BotStrategy(
            name="Nash Fireline",
            trade_weight=0.32369146686967376,
            raid_weight=3.1988427334095237,
            guard_weight=0.2647021501068245,
            fire_weight=3.2646768322154216,
            build_priority=[
                "guard_captain",
                "fishing_boat",
                "admiralty",
                "overtime",
                "fishing_dock",
                "fire_plans",
                "dry_dock",
                "admiral",
            ],
            convoy_bias=0.5921148217036665,
            ship_bias=0.7594042041053094,
            shipyard_bias=0.1347485091808977,
            fort_bias=0.09178978676684409,
            trade_guild_bias=0.09401226583653838,
            fishing_dock_bias=0.677382537455761,
            fishing_boat_bias=0.8139313881970534,
            guard_captain_bias=0.13681900579190934,
            fire_plans_bias=0.4368188642067561,
            dry_dock_bias=0.2290602773853748,
            admiralty_bias=0.32819645926129626,
            admiral_bias=0.22424933165492264,
            overtime_bias=0.7930686453505076,
            repair_bias=0.14586993575674678,
            construction_idle_bias=0.2367567825180562,
            opening_book=NASH_CORE_OPENING_BOOK,
        ),
        BotStrategy(
            name="Crown Ledger",
            trade_weight=4.005317240004103,
            raid_weight=1.9595210631848645,
            guard_weight=0.4777182500931804,
            fire_weight=2.0271128767645825,
            build_priority=[
                "guard_captain",
                "admiralty",
                "admiral",
            ],
            convoy_bias=0.9961560872637355,
            ship_bias=0.92842502574076,
            shipyard_bias=0.023518730196242135,
            fort_bias=0.01790044687004286,
            trade_guild_bias=0.07424809427942114,
            fishing_dock_bias=0.06012764385269903,
            fishing_boat_bias=0.7295136775954751,
            guard_captain_bias=0.826379346751287,
            fire_plans_bias=0.33226767407755087,
            dry_dock_bias=0.47837664093274734,
            admiralty_bias=0.7301085162980401,
            admiral_bias=0.5600620266505761,
            overtime_bias=0.3624648413070583,
            repair_bias=0.336405243590705,
            construction_idle_bias=0.9007981491962945,
        ),
        BotStrategy(
            name="Port Reaper",
            trade_weight=1.4,
            raid_weight=3.33,
            guard_weight=0.05,
            fire_weight=3.07,
            build_priority=[],
            convoy_bias=0.03,
            ship_bias=0.74,
        ),
        BotStrategy(
            name="Harbor Lock",
            trade_weight=4.72,
            raid_weight=0.68,
            guard_weight=3.6,
            fire_weight=2.0,
            build_priority=[],
            convoy_bias=0.18,
            ship_bias=0.9,
        ),
        BotStrategy(
            name="Corsair Spark",
            trade_weight=4.4,
            raid_weight=4.01,
            guard_weight=1.55,
            fire_weight=4.31,
            build_priority=[],
            convoy_bias=0.69,
            ship_bias=0.16,
        ),
        BotStrategy(
            name="Storm Reaver",
            trade_weight=2.84,
            raid_weight=3.95,
            guard_weight=2.19,
            fire_weight=4.61,
            build_priority=[],
            convoy_bias=0.32,
            ship_bias=0.74,
        ),
        BotStrategy(
            name="Iron Tempest",
            trade_weight=2.61,
            raid_weight=4.06,
            guard_weight=2.4,
            fire_weight=4.44,
            build_priority=[],
            convoy_bias=0.04,
            ship_bias=0.8,
        ),
        BotStrategy(
            name="Black Ledger",
            trade_weight=0.76,
            raid_weight=4.8,
            guard_weight=0.93,
            fire_weight=2.28,
            build_priority=[],
            convoy_bias=0.0,
            ship_bias=0.64,
            shipyard_bias=0.43,
            fort_bias=0.02,
            trade_guild_bias=0.12,
            guard_captain_bias=0.08,
            fire_plans_bias=0.12,
            construction_idle_bias=0.74,
        ),
        BotStrategy(
            name="Bastion Corsair",
            trade_weight=0.74,
            raid_weight=4.58,
            guard_weight=0.21,
            fire_weight=1.7,
            build_priority=[],
            convoy_bias=0.0,
            ship_bias=0.46,
            shipyard_bias=0.23,
            fort_bias=0.21,
            trade_guild_bias=0.08,
            guard_captain_bias=0.01,
            fire_plans_bias=0.04,
            construction_idle_bias=0.69,
        ),
        BotStrategy(
            name="Harbor Harvest",
            trade_weight=0.17,
            raid_weight=4.88,
            guard_weight=2.10,
            fire_weight=0.22,
            build_priority=[
                "fishing_dock",
                "shipyard",
                "fire_plans",
                "fishing_boat",
            ],
            convoy_bias=0.00,
            ship_bias=0.40,
            shipyard_bias=0.07,
            fort_bias=0.74,
            trade_guild_bias=0.29,
            fishing_dock_bias=1.00,
            fishing_boat_bias=0.99,
            guard_captain_bias=0.41,
            fire_plans_bias=0.34,
            construction_idle_bias=0.61,
        ),
        BotStrategy(
            name="Reef Tyrant",
            trade_weight=0.19,
            raid_weight=4.66,
            guard_weight=0.01,
            fire_weight=0.27,
            build_priority=[
                "fishing_boat",
                "fort",
                "fishing_dock",
                "shipyard",
                "fire_plans",
                "trade_guild",
            ],
            convoy_bias=0.00,
            ship_bias=0.80,
            shipyard_bias=0.04,
            fort_bias=0.24,
            trade_guild_bias=0.06,
            fishing_dock_bias=0.91,
            fishing_boat_bias=0.70,
            guard_captain_bias=0.10,
            fire_plans_bias=0.94,
            construction_idle_bias=0.72,
        ),
        BotStrategy(
            name="Reef Bloom",
            trade_weight=0.00,
            raid_weight=1.12,
            guard_weight=0.09,
            fire_weight=3.74,
            build_priority=[
                "fishing_dock",
                "dry_dock",
                "fishing_boat",
                "shipyard",
                "guard_captain",
                "fort",
                "fire_plans",
            ],
            convoy_bias=0.00,
            ship_bias=0.14,
            shipyard_bias=0.10,
            fort_bias=0.82,
            trade_guild_bias=0.00,
            guard_captain_bias=0.18,
            fire_plans_bias=0.15,
            fishing_dock_bias=0.99,
            fishing_boat_bias=0.97,
            dry_dock_bias=0.68,
            repair_bias=0.83,
            construction_idle_bias=0.43,
        ),
        BotStrategy(
            name="The Red Tide",
            trade_weight=0.33,
            raid_weight=4.89,
            guard_weight=0.00,
            fire_weight=1.41,
            build_priority=["shipyard"],
            convoy_bias=0.00,
            ship_bias=0.85,
            shipyard_bias=0.25,
            fort_bias=0.06,
            trade_guild_bias=0.01,
            guard_captain_bias=0.00,
            fire_plans_bias=0.00,
            construction_idle_bias=0.85,
        ),
        BotStrategy(
            name="Signal Black",
            trade_weight=0.02,
            raid_weight=4.16,
            guard_weight=0.02,
            fire_weight=0.17,
            build_priority=[],
            convoy_bias=0.01,
            ship_bias=0.89,
            shipyard_bias=0.03,
            fort_bias=0.03,
            trade_guild_bias=0.00,
            guard_captain_bias=0.08,
            fire_plans_bias=0.00,
            fishing_dock_bias=0.00,
            fishing_boat_bias=0.90,
            construction_idle_bias=0.46,
        ),
        BotStrategy(

            name="Gray Admiralty",

            trade_weight=3.0536330290457863,
            raid_weight=2.9059088637605175,
            guard_weight=2.693119153745268,
            fire_weight=3.3294622865948718,

            build_priority=[
                "dockhand",
                "guard_captain",
                "administrator",
                "fishing_dock",
                "fire_plans",
                "fishing_boat",
                "dockhouse",
                "admiralty",
                "admiral",
                "dry_dock",
            ],

            convoy_bias=0.9882523832598497,
            ship_bias=0.9560966965718832,

            shipyard_bias=0.060021254355232624,
            fort_bias=0.5017330941367448,
            trade_guild_bias=0.11200618577408271,
            administrator_bias=0.7702884103053237,

            guard_captain_bias=0.2025532728899971,
            fire_plans_bias=0.4305579223840103,

            fishing_dock_bias=0.3833657187764549,
            fishing_boat_bias=0.18592590841399306,

            dockhouse_bias=0.4233609121210691,
            dockhand_bias=0.5312021477638436,
            dockhand_repair_bias=0.13146267943065365,
            dockhand_boatwright_bias=0.8993476153729102,

            dry_dock_bias=0.4071141891002335,
            admiralty_bias=0.7671120240063621,
            admiral_bias=0.35779045206618576,
            overtime_bias=0.8430932269120164,

            repair_bias=0.5792499555209782,
            construction_idle_bias=0.23604171342371918,

            adaptive=False,
            adaptation_strength=0.0,
            adaptation_turns=3,
),
    ]


def strategy_names():
    return [strategy.name for strategy in default_bot_strategies()]


def find_strategy(name):
    """Find a BotStrategy by name from the default roster.
    Args:    name (str): The name of the strategy to find. The search is case-insensitive and ignores leading/trailing whitespace.
    Returns:    BotStrategy: The BotStrategy instance with the matching name.
    Raises:    ValueError: If no strategy with the given name is found in the default roster, with a message listing the available strategy names.
    """
    normalized_name = name.strip().lower()
    for strategy in default_bot_strategies():
        if strategy.name.lower() == normalized_name:
            return strategy

    available = ", ".join(strategy_names())
    raise ValueError(f"Unknown AI strategy '{name}'. Available strategies: {available}.")
